### ISSUE TITLE
Question- Can Conflicts occur between GPO & registery entries?

### ISSUE THREAD

**Issue by ls-milkyway** [simeononsecurity/Standalone-Windows-STIG-Script#2]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Hi !
Does your script add/remove registry entries without reflecting the changes in the GPO? This is the main problem with hardening scripts ....for example [HardeningKitty ](https://github.com/0x6d69636b/windows_hardening)....it's not possible to keep track of the both....conflicts can occur if user later change settings in GPO without checking it's related or created new registry entries.

**Comment by simeononsecurity** [comment]
Yes, some hardening requirements and recommendations aren't available via GPO so they are often done with registry. 
However, if GPO's become available and the registry is already set, often they show in the local gpo as well as any gpo changes will override them. You can review the script to see those changes. There are far too many to list.
Additionally many of the FireFox, Java, and .NET STIGs have changes that have never been available via gpo so those are also made available via the script.

With any script out there, trust but verify. Never run in production and test in a test/dev environment before rolling out.
We've put our scripts through a lot of testing, however every environment is different. YMMV

https://github.com/simeononsecurity/Standalone-Windows-STIG-Script/blob/master/secure-standalone.ps1

**Comment by ls-milkyway** [comment]
> However, if GPO's become available and the registry is already set, often they show in the local gpo as well as any gpo changes will override them. You can review the script to see those changes.

Hmm, thanks for quick reply but I guess this may not be true in every case...for eg. in the case of [HardeningKitty:
](https://github.com/0x6d69636b/windows_hardening)
In file "finding_list_msft_security_baseline_windows_10_22h2_machine.csv"

ID: 11001,"Administrative Templates: Windows Components","Windows Ink Workspace: Allow Windows Ink Workspace"

creates registry entry HKLM:\Software\Policies\Microsoft\WindowsInkWorkspace,AllowWindowsInkWorkspace as 1
but gpedit.msc shows it "Not Configured" ??

Because the group policy editor uses the registry.pol file to store all settings and does not read it from the registry. And HardeningKitty HailMary does not put entries in that file. Therefore, you can't see the configuration in gpedit.

Did you check such typical entries in your script that do not reflect in GPO OR your script is free from such conflicts?

Instead of using .ps script how can I automate importation of all possible non-conflicting settings via ADMX as I cannot use GPMC on non-AD standalone Win10 pro 22h2 PC? Analyzing all entries via ADMX/Policy Analyzer and implementing them will take lot of time?
Also the purpose of automation is defeated if I have to go through all settings (to check what it does &/or if it created a registry entry that is not reflected in GPO.
Why not ask user for yes/no for all settings in .ps script with small description or link to the details of the settings which clearly states what it does, is it available in GPO ....date of addition etc.?

**Comment by simeononsecurity** [comment]
We've never claimed our scripts are free of bugs. However, if you use the normal tools for scanning registries like SCAP or many others it comes down to roughly 90%-95% compliance minus any of the documentation requirements.  Some changes are redundant as some GPO settings don't actually apply if you use LGPO to apply them. For instance the audit policies. 

If you're limited to just using GPO, you're shooting yourself in the foot to begin with. You're more than welcome to create a bunch of custom ADMX files to apply most of the missing configurations. But if the configuration isn't already available via GPO or registry than you're going to be out of luck. Like we mention previously, there are many hardening configurations that can't be applied via GPO or registry. 

Generally speaking you should take any automation script or tool with a grain of salt. Every tool should be carefully analyzed at least once and that tool should be monitored for updates and tested in a testing/dev environment each time changes are made. 
Once you've analyzed it once, you know the end configuration state of all following runs. So the automation isn't defeated. You're just analyzing once instead of analyzing multiple times., If you're doing things correctly, this is the best result available.

There are three ways you have to analyze this script as it does three different things:
1.) Imports preconfigured GPO policies via the LGPO application.  This is because of the ease of keeping the GPOs up to date without having to relegate to converting documentation from GPOs to registries each time new STIGs or guidance comes out. This is big because without this we'd likely only have yearly releases or updates. Once imported to a test system you can use LGPO or RSOP to analyze the changes made using the GPO policy templates.
2.) Registry changes. There are no nested registry changes on this script. All are available via the main launcher script.
Anything that isn't standard or easily reviewable is commented with links to documentation inside the script.  Generally everything is commented with what the changes are actually doing where possible.  Note: There are some non-STIG related optimizations and hardening changes here that include industry standard mitigations that would be picked up on vulnerability scanners that also are applied via registry. You can see those it the mitigations, optimizations, and nessus sections.
3.) The FireFox, Java, and .Net hardening all require reviewing configuration files available in the files directory of this repo. Documentation needed to understand them is linked either in the readme or in the script. 
To answer your question about a yes/no option or creating a GUI... The yes/no options are problematic. There are tens of thousands of changes this script makes. Documenting each one would take longer than automating them and they change often. This is something we'd love to be able to achieve, but as a free and open source project it's very unlikely. Additionally, the majority of them are already documented via third party in [readme](https://github.com/simeononsecurity/Standalone-Windows-STIG-Script#additional-configurations-were-considered-from). 

These automation scripts where always designed to be headless and used by people who understand what they are doing. We could go out of our way to add a GUI or some other yes no options, but that would take an unreasonable about of time on our part and the end users part. There is some argument to allow you to run it once and generate like an XML list of the options you chose, but again at that point it just isn't worth the time sync. Also the amount of configuration resolution you'd have from that would always result in complaints. Either too many options or not enough. Again, this isn't a paid tool. 

Now, we do also have our [SCDP](https://github.com/simeononsecurity/STIG-Compliant-Domain-Prep) repo that only makes GPO related changes but is optimized to be imported into a domain controller.  It also includes all the GPO policies we've designed that are a bit above the STIG requirements. You could easily pick and choose the policies you want from there and manually import them using the LGPO tool if you wanted. However, if you want the FireFox, Java, or some of the missing .NET STIG changes you'll need the individualized versions of those scripts as documented in the readme of that repo.
