### ISSUE TITLE
Credential manager (windows credential)

### ISSUE THREAD

**Issue by Nexium57** [simeononsecurity/Standalone-Windows-STIG-Script#6]
Hello,
I executed the script, but it deactivates the windows credential in the credential manager.
I would not like it to be deactivated because I lose the connection to my network drives when starting my PC.

Thank you in advance for your answer.

**Comment by simeononsecurity** [comment]
> Hello, I executed the script, but it deactivates the windows credential in the credential manager. I would not like it to be deactivated because I lose the connection to my network drives when starting my PC.
> 
> Thank you in advance for your answer.

If it deactivates it, it's likely because whatever you're doing is too insecure to allow. We try to be minimally invasive but somethings just should never be compromised on.  This is also a STIG script which does have a required baseline configuration as well.  I know this issue would persist with mounted network folders, but for network shares we haven't seen any issues unless we're talking SMB1 or SMB2 connectivity.  Credential manager is restricted per the STIG as well.
I suggest you familiarize yourself with https://www.stigviewer.com/stig/windows_10/ and see what options you might need to disable.

If you're not an enterprise user, I suggest you use this script in the future instead.

https://github.com/simeononsecurity/Windows-Optimize-Harden-Debloat

It implements the stigs in a much more forgiving way.
